version: 0.2
#https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

phases:
  pre_build:
    commands:
      - # REPOSITORY_URI	197295423253.dkr.ecr.us-west-2.amazonaws.com/laravel-test2	PLAINTEXT
      - # dockerhub_username	arn:aws:secretsmanager:us-west-2:197295423253:secret:ashain_dockerhub-vB7Ahk:username	SECRETS_MANAGER
      - # dockerhub_password	arn:aws:secretsmanager:us-west-2:197295423253:secret:ashain_dockerhub-vB7Ahk:password	SECRETS_MANAGER
      - # AWS_REGION	us-west-2	PLAINTEXT
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $REPOSITORY_URI
      - echo docker login -u $dockerhub_username -p $dockerhub_password
      - docker login -u $dockerhub_username -p $dockerhub_password
      - docker build -t $REPOSITORY_URI:latest ./aws
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"laravel-test2-cnt","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
